ALMS-211 GitHub action added for unit test
makeen-project/amazon-location-mobile-auth-sdk-android pull request #18
Opened 2024-07-02 10:59 UTC by shah279

feat: GitHub action added for unit test

2024-07-03 13:41 UTC, olegfilimonov requested changes

2024-07-03 13:41 UTC, olegfilimonov commented on .github/workflows/test-android.yml
> +    runs-on: macos-13
why macos? Cant we use ubuntu?

2024-07-03 14:00 UTC, shah279 commented on .github/workflows/test-android.yml
> +    runs-on: macos-13
Yes, Updated

2024-07-04 13:09 UTC, olegfilimonov approved these changes

2024-07-04 13:09 UTC, merged